export const GET_MENU_LOADING = 'GET_MENU_LOADING'
export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS'
export const GET_MENU_FAIL = 'GET_MENU_FAIL'

export const GET_CUR_USER_SUCCESS = 'GET_CUR_USER_SUCCESS'
export const GET_CUR_USER_FAIL = 'GET_CUR_USER_FAIL'
