export const GET_MENU_LOADING = 'GET_MENU_LOADING'
export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS'
export const GET_MENU_FAIL = 'GET_MENU_FAIL'

export const GET_CUR_USER_SUCCESS = 'GET_CUR_USER_SUCCESS'
export const GET_CUR_USER_FAIL = 'GET_CUR_USER_FAIL'

export const ADD_CART_ITEM = 'ADD_CART_ITEM'
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM'
export const DELETE_CART = 'DELETE_CART'
export const REMOVE_CART_ADDED = 'REMOVE_CART_ADDED'

export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST'
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS'
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL'

export const GET_ALL_ORDERS_REQUEST = 'GET_ALL_ORDERS_REQUEST'
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS'
export const GET_ALL_ORDERS_FAIL = 'GET_ALL_ORDERS_FAIL'

export const SUBMIT_ORDERS_REQUEST = 'SUBMIT_ORDERS_REQUEST'
export const SUBMIT_ORDERS_SUCCESS = 'SUBMIT_ORDERS_SUCCESS'
export const SUBMIT_ORDERS_FAIL = 'SUBMIT_ORDERS_FAIL'

export const SET_ORDER_TIMEOUT = 'SET_ORDER_TIMEOUT'
export const RESET_ORDER_TIMEOUT = 'RESET_ORDER_TIMEOUT'
